---
- name: Reboot all hosts
  hosts: all
  gather_facts: false
  become: true

  vars:
    reboot_timeout: 600

  tasks:
    - name: Reboot hosts
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        test_command: whoami
