---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  extensions:
    helm:
      repositories:
        - name: traefik
          url: https://helm.traefik.io/traefik
        - name: metallb
          url: https://metallb.github.io/metallb
        - name: cert-manager
          url: https://charts.jetstack.io
        - name: argocd
          url: https://argoproj.github.io/argo-helm
      charts:
        - name: cert-manager
          chartname: jetstack/cert-manager
          version: v1.18.2
          namespace: cert-manager
          values: |
            installCRDs: true
        - name: argocd
          chartname: argocd/argo-cd
          version: 8.2.7
          namespace: argocd
        - name: traefik
          chartname: traefik/traefik
          version: 37.0.0
          namespace: traefik-system
          values: |
            service:
              enabled: true
              type: LoadBalancer
              externalIPs: [192.168.8.20]
        - name: metallb
          chartname: metallb/metallb
          version: 0.15.2
          namespace: metallb-system
          values: |
            configInline:
              address-pools:
                - name: generic-cluster-pool
                  protocol: layer2
                  addresses:
                    - 192.168.8.20-192.168.8.30
  hosts:
    - ssh:
        address: 192.168.8.100
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller
    - ssh:
        address: 192.168.8.101
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller
    - ssh:
        address: 192.168.8.102
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 192.168.8.103
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 192.168.8.104
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
