apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argot-clusterlab-cc
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - argo.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
