apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-clusterlab-cc
  namespace: media-system
spec:
  secretName: qbittorrent-clusterlab-cc-tls
  dnsNames:
    - qbittorrent.clusterlab.cc
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
