# Root Argo CD Application (App of Apps pattern)
# This application will sync all Argo CD Application manifests stored under argocd/apps
# in the homelab repository.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: homelab-root
    app.kubernetes.io/part-of: homelab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/kamil-alekber/homelab.git
    targetRevision: main
    path: argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
