apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: quay.io/jetstack/charts
    targetRevision: v1.18.2
    helm:
      skipCrds: false
      releaseName: cert-manager
      values: |
        installCRDs: true
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
