apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: community-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: community-charts
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.14.1
    helm:
      releaseName: n8n
      values: |
        # Add your values here
  destination:
    name: in-cluster
    namespace: n8n
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
