apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kamil-alekber/homelab
      path: argocd/manifests/external-dns
      targetRevision: HEAD
    - chart: external-dns
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 9.0.3
      helm:
        releaseName: external-dns
        values: |
          provider: webhook
          extraArgs:
            webhook-provider-url: http://localhost:8888
          sidecars:
            - name: adguard-webhook
              image: ghcr.io/muhlba91/external-dns-provider-adguard:$RELEASE_VERSION
              ports:
                - containerPort: 8888
                  name: http
                - containerPort: 8080
                  name: healthz
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 5
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 5
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: ADGUARD_URL
                  valueFrom:
                    secretKeyRef:
                      name: adguard-configuration
                      key: url
                - name: ADGUARD_USER
                  valueFrom:
                    secretKeyRef:
                      name: adguard-configuration
                      key: user
                - name: ADGUARD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: adguard-configuration
                      key: password
                - name: DRY_RUN
                  value: "false"

  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
