apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.19.2
      helm:
        releaseName: external-secrets
        values: |
          installCRDs: true
    - repoURL: https://github.com/kamil-alekber/homelab
      path: argocd/manifests/external-secrets
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
