apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-stack
  namespace: argocd
spec:
  project: default
  source:
    - chart: app-template
      repoURL: ghcr.io/bjw-s-labs/helm/app-template
      targetRevision: 4.2.0
      helm:
        releaseName: prowlarr
  destination:
    name: in-cluster
    namespace: media-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
