apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.15.2
      helm:
        releaseName: metallb
    - repoURL: https://github.com/kamil-alekber/homelab.git
      targetRevision: main
      path: "argocd/apps/metallb-config"
  destination:
    name: in-cluster
    namespace: metallb
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
