apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    chart: n8n
    repoURL: 8gears.container-registry.com/library
    targetRevision: 1.0.10
    helm:
      releaseName: n8n
      values: |
        # Add your values here
  destination:
    name: in-cluster
    namespace: n8n
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
