apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/latest
    targetRevision: 2.12.0
    helm:
      releaseName: rancher
      values: |
        hostname: rancher.clusterlab.cc
        bootstrapPassword: 95782641
  destination:
    name: in-cluster
    namespace: cattle-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
