apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd
spec:
  project: default
  source:
    chart: csi-driver-smb
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    targetRevision: v1.18.0
    helm:
      releaseName: csi-driver-smb
      # kubelet path for k0s distro: /var/lib/k0s/kubelet
      values: |
        linux:
          kubelet: /var/lib/k0s/kubelet
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
