apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kamil-alekber/homelab
    path: argocd/apps/whoami
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: whoami
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
