---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudcmd
  namespace: media-system
spec:
  secretName: cloudcmd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - files.clusterlab.cc
